# Generated by Django 5.2.12 on 2026-04-02 07:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('farmers', '0001_initial'),
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DistributionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_released', models.PositiveIntegerField()),
                ('distribution_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Released', 'Released'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20)),
                ('remarks', models.TextField(blank=True)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distribution_records', to='farmers.farmerprofile')),
                ('input_inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distribution_records', to='inventory.inputinventory')),
                ('release_officer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='released_distributions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-distribution_date'],
            },
        ),
    ]
