# Generated by Django 5.2.12 on 2026-04-02 07:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distributions', '0001_initial'),
        ('distributors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='distributionrecord',
            name='assigned_distributor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='distribution_records', to='distributors.distributor'),
        ),
    ]
