# Generated by Django 5.2.12 on 2026-04-02 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distributions', '0002_distributionrecord_assigned_distributor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distributionrecord',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Released', 'Released'), ('Delivered', 'Delivered'), ('Delayed', 'Delayed'), ('Rescheduled', 'Rescheduled'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20),
        ),
    ]
