# Generated by Django 5.2.12 on 2026-04-02 07:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('programs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FarmerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('address', models.TextField()),
                ('contact_number', models.CharField(max_length=30)),
                ('credentials_status', models.CharField(choices=[('Verified', 'Verified'), ('Pending', 'Pending'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('farm_location', models.CharField(max_length=255)),
                ('planting_season', models.CharField(max_length=100)),
                ('date_registered', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='farmer_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='InterventionApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('remarks', models.TextField(blank=True)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='farmers.farmerprofile')),
                ('intervention', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='programs.intervention')),
            ],
            options={
                'ordering': ['-application_date'],
                'unique_together': {('farmer', 'intervention')},
            },
        ),
    ]
