# Generated by Django 5.2.12 on 2026-04-02 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Distributor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('services_offered', models.TextField()),
                ('accreditation_status', models.CharField(choices=[('Accredited', 'Accredited'), ('Pending', 'Pending'), ('Suspended', 'Suspended')], default='Pending', max_length=20)),
                ('contact_person', models.CharField(max_length=255)),
                ('contact_number', models.CharField(max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
